### ISSUE TITLE
MIT License Choice

### ISSUE THREAD

**Issue by schepal** [UBC-MDS/nlpsummarizer#64]
We collectively believe that the MIT license best fits the needs of this project. We want to make it easy for users to test our library with little concern for legal ramifications. This license also provides the flexibility for corporations to experiment with our software without having to ask for a private license. Lastly, the MIT license allows us to share this software without any warranty, hence protecting the software developers in the case there is a bug or error when using this library.

**Comment by vigchandra** [comment]
MIT license has been added and hence closing this issue.
